export const alcohol = [
  {
    id: 1,
    type: "alcohol",
    name: "Gelati",
    description: `(Грузія, сорт винограду Сапераві) біле/червоне н/с`,
    price: "100мл - 50грн/0.75л - 275грн",
  },
  {
    id: 9,
    type: "alcohol",
    name: "Alazani Valley Mimino",
    description: `(Грузія, сорт винограду Ркацителі, Цолікаурі) біле н/с`,
    price: "295грн",
  },
  {
    id: 10,
    type: "alcohol",
    name: "Alazani Valley Mimino",
    description: `(Грузія , сорт винограду Александроулі, Муджуретулі, Оджалеші, Сапераві) червоне н/с`,
    price: "295грн",
  },
  {
    id: 13,
    type: "alcohol",
    name: "Miriani pirosmani",
    description: `Червоне н/сухе. Сорт винограду Мускат, Оджалеші, Сапераві`,
    price: "295грн",
  },
  {
    id: 14,
    type: "alcohol",
    name: "Miriani Pirosmani",
    description: "Біле н/сухе. Сорт винограду Мцване, Ркацителі",
    price: "50мл - 60грн/0.5л - 600грн",
  },
  {
    id: 2,
    type: "alcohol",
    name: "Asti",
    description: "Шампанське біле",
    price: "275грн",
  },
  {
    id: 12,
    type: "alcohol",
    name: "Asti",
    description: "Шампанське рожеве",
    price: "275грн",
  },
  {
	id: 17,
	type: "alcohol",
	name: "GALAKTIONI",
	description: "BRUT",
	price: "400грн",
 },
 {
	id: 18,
	type: "alcohol",
	name: "GALAKTIONI",
	description: "Semi-sweet",
	price: "400грн",
 },
  {
    id: 3,
    type: "alcohol",
    name: "Fragolino (Італія біле)",
    description: "",
    price: "250грн",
  },
  {
    id: 4,
    type: "alcohol",
    name: "Fragolino (Італія червоне)",
    description: "",
    price: "250грн",
  },
  {
    id: 5,
    type: "alcohol",
    name: "Jack Daniels",
    description: "",
    price: "50мл - 100грн/0.5л - 1000грн/0.7л - 1300грн",
  },
  {
    id: 6,
    type: "alcohol",
    name: "Jim Beam",
    description: "",
    price: "50мл - 85грн/0.5л - 800грн/0.7л - 1200грн",
  },
  {
    id: 7,
    type: "alcohol",
    name: "Jim Beam Apple",
    description: "",
    price: "85грн - 50мл",
  },
  {
    id: 11,
    type: "alcohol",
    name: "Capitan Morgan",
    description: "",
    price: "50мл - 60грн/0.5л - 600грн",
  },
  {
    id: 8,
    type: "alcohol",
    name: "Jägermeister",
    description: "",
    price: "50мл - 70грн/0.5л - 700грн",
  },
  {
    id: 15,
    type: "alcohol",
    name: "Старий кахеті 3 роки",
    description: ``,
    price: "375грн",
  },
  {
    id: 16,
    type: "alcohol",
    name: "Старий кахеті 5 років",
    description: "",
    price: "400грн",
  },
];
