export const appetizer = [
  {
    id: 1,
    type: "appetizer",
    name: "Брускети з лососем і авокадо (3 шт)",
    description: "",
    price: "150 грн",
  },
  {
    id: 2,
    type: "appetizer",
    name: "Брускети з брі та грушею (3 шт)",
    description: "",
    price: "125 грн",
  },
  {
    id: 3,
    type: "appetizer",
    name: "Брускети з прошуто та в‘яленими томатами (3 шт)",
    description: "",
    price: "125 грн",
  },
  {
    id: 4,
    type: "appetizer",
    name: "Сирне плато 375 г",
    description: "Брі, дор-блю, гауда, сир з базиліком, виноград, оливки",
    price: "225 грн",
  },
  {
    id: 5,
    type: "appetizer",
    name: "М’ясне плато 400 г",
    description: "Прошуто, салямі, шинка, фует, маринований перець чилі",
    price: "275 грн",
  },
  {
    id: 6,
    type: "appetizer",
    name: "Фрі-сет  600 г",
    description:
      "Нагетси, сирні палички, фрі, кільця кальмарів, стріпси, чіпси",
    price: "500 грн",
  },
  {
    id: 7,
    type: "appetizer",
    name: "Велике плато холодних закусок",
    description:
      "Сири: брі, дор-блю, сир з базиліком, гауда, салямі, шинка, фарширований перець чилі, виноград, оливки",
    price: "500 грн",
  },
  {
    id: 8,
    type: "appetizer",
    name: "Равлики по-бургунські",
    description: "",
    price: "150 грн",
  },
  {
    id: 9,
    type: "appetizer",
    name: "Равлики медово-гірчичні",
    description: "",
    price: "150 грн",
  },
  {
    id: 10,
    type: "appetizer",
    name: "Равлики по-прованські",
    description: "",
    price: "150 грн",
  },
  {
    id: 11,
    type: "appetizer",
    name: "Устриці Fine de Clair",
    description: "Франція, Атлантичний океан",
    price: "120 грн/1 шт",
  },
  {
    id: 12,
    type: "appetizer",
    name: "Устриці Saint Patrick",
    description: "Ірландія, Атлантичний океан",
    price: "150 грн/ 1 шт",
  },
  {
    id: 13,
    type: "appetizer",
    name: "Устриці Fine de Clair",
    description: "Франція, Атлантичний океан",
    price: "450 грн/4 шт",
  },
  {
    id: 14,
    type: "appetizer",
    name: "Устриці Saint Patrick",
    description: "Ірландія, Атлантичний океан",
    price: "550 грн/ 4 шт",
  },
  {
    id: 15,
    type: "appetizer",
    name: "Дюжина устриць Fine de Clair",
    description: "",
    price: "1350 грн/12 шт",
  },
  {
    id: 16,
    type: "appetizer",
    name: "Дюжина устриць Saint Patrick",
    description: "",
    price: "1500 грн/12 шт",
  },
  {
    id: 17,
    type: "appetizer",
    name: "Устриця запечена",
    description: "",
    price: "150 грн/1 шт",
  },
  {
    id: 18,
    type: "appetizer",
    name: "Сет запечених устриць",
    description: "",
    price: "600 грн/4 шт",
  },
    {
    id: 19,
    type: "appetizer",
    name: "Хлібна нарізка",
    description: "",
    price: "20 грн",
  },
];
