export const cocktail = [
  {
    id: 1,
    type: "cocktail",
    name: "Aperol Spritz",
    description: "Aperol, просеко, швепс, гренадин, лід",
    price: "150 грн",
  },
  {
    id: 2,
    type: "cocktail",
    name: "Mojito",
    description: "Ром, спрайт, лайм, м’ята, лід",
    price: "150 грн",
  },
  {
    id: 3,
    type: "cocktail",
    name: "Jägermeister Mojito",
    description: "М’ята, лайм,лід, jäegermeister, спрайт",
    price: "150 грн",
  },
  {
    id: 4,
    type: "cocktail",
    name: "Jäeger Bomb",
    description: "Jäegermeister, burn, лід",
    price: "125 грн",
  },
  {
    id: 5,
    type: "cocktail",
    name: "Cuba libre",
    description: "Ром, кола, лимонний сік, лід",
    price: "125 грн",
  },
  {
    id: 6,
    type: "cocktail",
    name: "Garibaldi",
    description: "Aperol, апельсиновий сік",
    price: "100 грн",
  },
  {
    id: 7,
    type: "cocktail",
    name: "Mimosa",
    description: "Просеко, апельсиновий фреш",
    price: "100 грн",
  },
  {
    id: 8,
    type: "cocktail",
    name: "Froze",
    description: "Просеко, пюре полуничне",
    price: "100 грн",
  },
];
