export const dessert = [
  {
    id: 1,
    type: "dessert",
    name: "Чізкейк солона карамель",
    description: "",
    price: "90 грн",
  },
  {
    id: 2,
    type: "dessert",
    name: "Брауні",
    description: "",
    price: "75 грн",
  },
  {
    id: 3,
    type: "dessert",
    name: "3 шоколада",
    description: "",
    price: "95 грн",
  },
  {
	id: 4,
	type: "dessert",
	name: "Еклер снікерс",
	description: "",
	price: "65 грн",
 },
 {
	id: 5,
	type: "dessert",
	name: "Еклер полуничний",
	description: "",
	price: "65 грн",
 },
 {
	id: 6,
	type: "dessert",
	name: "Еклер груша дор-блю",
	description: "",
	price: "65 грн",
 },
 {
	id: 7,
	type: "dessert",
	name: "Макаронс в асортименті",
	description: "",
	price: "50 грн/1 шт",
 },
];
