export const dessert = [
  {
    id: 1,
    type: "dessert",
    name: "Чізкейк солона карамель",
    description: "",
    price: "90 грн",
  },
  {
    id: 3,
    type: "dessert",
    name: "3 шоколада",
    description: "",
    price: "95 грн",
  },
  {
	id: 4,
	type: "dessert",
	name: "Еклер снікерс",
	description: "",
	price: "65 грн",
 },
 {
	id: 5,
	type: "dessert",
	name: "Еклер полуничний",
	description: "",
	price: "65 грн",
 },
 {
	id: 6,
	type: "dessert",
	name: "Еклер груша дор-блю",
	description: "",
	price: "65 грн",
 },
 {
	id: 7,
	type: "dessert",
	name: "Макаронс в асортименті",
	description: "",
	price: "50 грн/1 шт",
 },
 {
	id: 8,
	type: "dessert",
	name: "Бельгійська вафля класична з морозивом і ягодами",
	description: "",
	price: "150 грн",
 },
 {
	id: 9,
	type: "dessert",
	name: "Сирники зі сметаною і джемом",
	description: "",
	price: "150 грн",
 },
 {
	id: 10,
	type: "dessert",
	name: "Млинці з сиром",
	description: "",
	price: "150 грн",
 },
];
