export const drink = [
  { id: 1, type: "drink", name: "Сік 1л", description: "", price: "75 грн" },
  { id: 2, type: "drink", name: "Сік 250мл", description: "", price: "25 грн" },
  {
    id: 3,
    type: "drink",
    name: "Coca-cola ж/б",
    description: "",
    price: "25 грн",
  },
  {
    id: 4,
    type: "drink",
    name: "Coca-cola 0,5л",
    description: "",
    price: "30 грн",
  },
  {
    id: 5,
    type: "drink",
    name: "Coca-cola 1л",
    description: "",
    price: "50 грн",
  },
  { id: 6, type: "drink", name: "Вода 0,5л", description: "", price: "25 грн" },
  {
    id: 7,
    type: "drink",
    name: "Комбуча 350мл",
    description: "",
    price: "75 грн",
  },
  {
    id: 8,
    type: "drink",
    name: "Лимонад класичний",
    description: "",
    price: "75 грн",
  },
  {
    id: 9,
    type: "drink",
    name: "Лимонад імбирний",
    description: "",
    price: "75 грн",
  },
  { id: 10, type: "drink", name: "Мілкшейк", description: "", price: "75 грн" },
  { id: 11, type: "drink", name: "Мохіто", description: "", price: "75 грн" },
  {
    id: 12,
    type: "drink",
    name: "Міккі Маус",
    description: "",
    price: "75 грн",
  },
];
