export const grill = [
  {
    id: 1,
    type: "grill",
    name: "Лосось та пюре з броколі",
    description: "",
    price: "325 грн",
  },
  {
    id: 2,
    type: "grill",
    name: "Куряча грудка з овочами та сирним соусом",
    description: "",
    price: "175 грн",
  },
  {
    id: 4,
    type: "grill",
    name: "Камамбер з томатами чері",
    description: "",
    price: "150 грн",
  },
  {
    id: 5,
    type: "grill",
    name: "Ребра BBQ",
    description: "",
    price: "175 грн",
  },
  {
    id: 7,
    type: "grill",
    name: "Крильця бафало",
    description: "",
    price: "150 грн",
  },
  {
	id: 8,
	type: "grill",
	name: "Стейк на кістці",
	description: '',
	price: "250 грн",
 },
 {
	id: 9,
	type: "grill",
	name: "Гриль мікс",
	description: '',
	price: "700 грн",
 },
 {
	id: 10,
	type: "grill",
	name: "Овочі гриль",
	description: '',
	price: "250 грн",
 },
 {
	id: 11,
	type: "grill",
	name: "Кордон-блю з картопляним пюре",
	description: '',
	price: "195 грн",
 },
];
