export const hotDrink = [
  {
    id: 1,
    type: "hotDrink",
    name: "Еспресо",
    description: "",
    price: "40 грн",
  },
  {
    id: 2,
    type: "hotDrink",
    name: "Американо",
    description: "",
    price: "40 грн",
  },
  {
    id: 3,
    type: "hotDrink",
    name: "Американо з молоком",
    description: "",
    price: "45 грн",
  },
  {
    id: 4,
    type: "hotDrink",
    name: "Флет вайт",
    description: "",
    price: "50 грн",
  },
  {
    id: 5,
    type: "hotDrink",
    name: "Капучіно",
    description: "",
    price: "50 грн",
  },
  { id: 6, type: "hotDrink", name: "Лате", description: "", price: "50 грн" },
  {
    id: 7,
    type: "hotDrink",
    name: "Лате на рослинному",
    description: "",
    price: "75 грн",
  },
  { id: 8, type: "hotDrink", name: "Какао", description: "", price: "50 грн" },
  {
    id: 9,
    type: "hotDrink",
    name: "Глінтвейн",
    description: "",
    price: "75 грн",
  },
  { id: 10, type: "hotDrink", name: "Чай", description: "", price: "50 грн" },
  {
    id: 11,
    type: "hotDrink",
    name: "Чай натуральний в асортименті",
    description: "",
    price: "35 грн",
  },
];
